### ISSUE TITLE
maxwall error when host is bcbl

### ISSUE THREAD

**Issue by MengxingLiu** [garikoitz/launchcontainers#17]
maxwall option is not used in the bcbl. either make this option optional, or set a default value when bcbl is the host.
![image](https://user-images.githubusercontent.com/15864071/163129978-12d13dda-433f-4c51-90c4-f364f75429af.png)

**Comment by garikoitz** [comment]
I added it and commited the result, at bcbl it works the same, the code needs to change to be more flexible in the future, so that any number of different hosts can use different params
