### ISSUE TITLE
Right now 'force' needs to be False in order to make it work

### ISSUE THREAD

**Issue by leandrolecca** [garikoitz/launchcontainers#23]
If it is not False, it will always use the example_config.json or example_tractparams.csv as we overwrite them all the time.

**Comment by yongninglei** [comment]
I need to check:

in func 5, how did the log file copied
-in config, do we really need logdir and tmpdir? maybe do some edit there as well as config.yaml

Need to implement:

Add one flag --check file, only some minor changes

add a check function inside function 5

add a different check function inside function 4, or modulize the check function in createsymlinks

**Comment by garikoitz** [comment]
Pasting here one of the issues with the new way of working, if it is not like that in the PR, we need to explain here before closing the issue: 

- Create a project folder
- Convert your dicoms with heudiconv
- Copy an example_config.yaml to nifti folder
- Edit example_config.yaml
- Create the symlinks by running 'python launchcontainers.py -lcc .... -cc .... -ssl ....' (always without --run_lc)
- Check that all the symlinks are successfully created and that the configs are copied (use 'tree' command with color coding to check that there are not broken links)
- 'cd' to nifti/derivatives/container_version/analysis-x/
- Edit config.json (tractparams.csv for the case of rtp-pipeline, etc..)
- Run the container by running 'python launchcontainers.py -lcc ./config_lc.yaml --run_lc'


Only the last step is different, as explained in the wiki

**Comment by yongninglei** [comment]
this issue is finished by my PR
